# Generated by Django 3.2.25 on 2024-06-28 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trekkapp', '0006_auto_20240625_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.IntegerField(max_length=10)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='enquire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.IntegerField(max_length=10)),
                ('message', models.TextField()),
                ('thetrek', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='personaltrek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.IntegerField(max_length=10)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='camping',
            name='date',
            field=models.DateField(default=datetime.date(2024, 6, 28)),
        ),
        migrations.AddField(
            model_name='camping',
            name='difficulty',
            field=models.CharField(default='easy', max_length=100),
        ),
        migrations.AddField(
            model_name='camping',
            name='fees',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='camping',
            name='inclusions',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='camping',
            name='info',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='camping',
            name='intro',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='camping',
            name='itenary',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='cycling',
            name='date',
            field=models.DateField(default=datetime.date(2024, 6, 28)),
        ),
        migrations.AddField(
            model_name='cycling',
            name='difficulty',
            field=models.CharField(default='easy', max_length=100),
        ),
        migrations.AddField(
            model_name='cycling',
            name='fees',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cycling',
            name='inclusions',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='cycling',
            name='info',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='cycling',
            name='intro',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='cycling',
            name='itenary',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='tours',
            name='date',
            field=models.DateField(default=datetime.date(2024, 6, 28)),
        ),
        migrations.AddField(
            model_name='tours',
            name='difficulty',
            field=models.CharField(default='easy', max_length=100),
        ),
        migrations.AddField(
            model_name='tours',
            name='fees',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tours',
            name='inclusions',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='tours',
            name='info',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='tours',
            name='intro',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tours',
            name='itenary',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='city',
            name='date',
            field=models.DateField(default=datetime.date(2024, 6, 28)),
        ),
        migrations.AlterField(
            model_name='city',
            name='itenary',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
