# Generated by Django 3.2.25 on 2024-06-29 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trekkapp', '0007_auto_20240628_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camping',
            name='date',
            field=models.DateField(default=datetime.date(2024, 6, 29)),
        ),
        migrations.AlterField(
            model_name='city',
            name='date',
            field=models.DateField(default=datetime.date(2024, 6, 29)),
        ),
        migrations.AlterField(
            model_name='cycling',
            name='date',
            field=models.DateField(default=datetime.date(2024, 6, 29)),
        ),
        migrations.AlterField(
            model_name='enquire',
            name='thetrek',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='tours',
            name='date',
            field=models.DateField(default=datetime.date(2024, 6, 29)),
        ),
    ]
