# Generated by Django 3.2.25 on 2024-07-08 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trekkapp', '0008_auto_20240629_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='camping',
            name='image',
            field=models.ImageField(default='LOGO.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='camping',
            name='map',
            field=models.CharField(default='<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3768.07931841176!2d72.82962437395439!3d19.19173764833135!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3be7b72e2cf5a19d%3A0xbe3acd83444503!2sTechno%20Graphix!5e0!3m2!1sen!2sin!4v1719401531201!5m2!1sen!2sin" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>', max_length=10000),
        ),
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.ImageField(default='LOGO.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='city',
            name='map',
            field=models.CharField(default='<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3768.07931841176!2d72.82962437395439!3d19.19173764833135!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3be7b72e2cf5a19d%3A0xbe3acd83444503!2sTechno%20Graphix!5e0!3m2!1sen!2sin!4v1719401531201!5m2!1sen!2sin" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>', max_length=10000),
        ),
        migrations.AddField(
            model_name='cycling',
            name='image',
            field=models.ImageField(default='LOGO.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='cycling',
            name='map',
            field=models.CharField(default='<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3768.07931841176!2d72.82962437395439!3d19.19173764833135!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3be7b72e2cf5a19d%3A0xbe3acd83444503!2sTechno%20Graphix!5e0!3m2!1sen!2sin!4v1719401531201!5m2!1sen!2sin" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>', max_length=10000),
        ),
        migrations.AddField(
            model_name='tours',
            name='image',
            field=models.ImageField(default='LOGO.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='tours',
            name='map',
            field=models.CharField(default='<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3768.07931841176!2d72.82962437395439!3d19.19173764833135!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3be7b72e2cf5a19d%3A0xbe3acd83444503!2sTechno%20Graphix!5e0!3m2!1sen!2sin!4v1719401531201!5m2!1sen!2sin" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>', max_length=10000),
        ),
        migrations.AlterField(
            model_name='camping',
            name='date',
            field=models.DateField(default=datetime.date(2024, 7, 8)),
        ),
        migrations.AlterField(
            model_name='city',
            name='date',
            field=models.DateField(default=datetime.date(2024, 7, 8)),
        ),
        migrations.AlterField(
            model_name='cycling',
            name='date',
            field=models.DateField(default=datetime.date(2024, 7, 8)),
        ),
        migrations.AlterField(
            model_name='tours',
            name='date',
            field=models.DateField(default=datetime.date(2024, 7, 8)),
        ),
    ]
