# Generated by Django 3.2.25 on 2024-07-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trekkapp', '0010_auto_20240709_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='exclude',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='festival',
            name='exclude',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trekking',
            name='exclude',
            field=models.BooleanField(default=False),
        ),
    ]
