# Generated by Django 3.2.25 on 2024-07-18 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trekkapp', '0015_auto_20240713_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaltrek',
            name='date',
            field=models.DateField(default=datetime.date(2024, 7, 18)),
        ),
        migrations.AlterField(
            model_name='camping',
            name='date',
            field=models.DateField(default=datetime.date(2024, 7, 18)),
        ),
        migrations.AlterField(
            model_name='city',
            name='date',
            field=models.DateField(default=datetime.date(2024, 7, 18)),
        ),
        migrations.AlterField(
            model_name='cycling',
            name='date',
            field=models.DateField(default=datetime.date(2024, 7, 18)),
        ),
        migrations.AlterField(
            model_name='tours',
            name='date',
            field=models.DateField(default=datetime.date(2024, 7, 18)),
        ),
    ]
