# Generated by Django 4.2.5 on 2024-09-03 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trekkapp', '0016_auto_20240719_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marquee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='camping',
            name='date',
            field=models.DateField(default=datetime.date(2024, 9, 3)),
        ),
        migrations.AlterField(
            model_name='city',
            name='date',
            field=models.DateField(default=datetime.date(2024, 9, 3)),
        ),
        migrations.AlterField(
            model_name='cycling',
            name='date',
            field=models.DateField(default=datetime.date(2024, 9, 3)),
        ),
        migrations.AlterField(
            model_name='personaltrek',
            name='date',
            field=models.DateField(default=datetime.date(2024, 9, 3)),
        ),
        migrations.AlterField(
            model_name='tours',
            name='date',
            field=models.DateField(default=datetime.date(2024, 9, 3)),
        ),
    ]
