# Generated by Django 4.2.5 on 2024-09-04 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trekkapp', '0017_marquee_alter_camping_date_alter_city_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camping',
            name='date',
            field=models.DateField(default=datetime.date(2024, 9, 4)),
        ),
        migrations.AlterField(
            model_name='city',
            name='date',
            field=models.DateField(default=datetime.date(2024, 9, 4)),
        ),
        migrations.AlterField(
            model_name='cycling',
            name='date',
            field=models.DateField(default=datetime.date(2024, 9, 4)),
        ),
        migrations.AlterField(
            model_name='personaltrek',
            name='date',
            field=models.DateField(default=datetime.date(2024, 9, 4)),
        ),
        migrations.AlterField(
            model_name='tours',
            name='date',
            field=models.DateField(default=datetime.date(2024, 9, 4)),
        ),
    ]
